apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: ghcr.io/akuity/kargo-charts
    chart: kargo
    targetRevision: 1.11.4

    helm:
      valuesObject:
        api:
          secret:
            name: kargo-admin

  destination:
    server: https://kubernetes.default.svc
    namespace: kargo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
