apiVersion: v1
kind: ConfigMap
metadata:
  name: kargo-api-ca
  namespace: kargo
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIICxzCCAa+gAwIBAgIUYose6+E94n2m8SN1bIKCpAj6zH8wDQYJKoZIhvcNAQEL
    BQAwADAeFw0yNjA5MjMyMTQ4MzhaFw0yNjEyMjIyMTQ4MzhaMAAwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDeva0AL3tUiJJIrlUtU/3iMQK/xQktzDr5
    IbWySy7hpuipvOhVunvxq7P+y5Hjf+rEilUHUpVIE/ISIpHGkNhLEf+bb2T9YM0j
    GcnQwQMpeKCOLlWx0IbsqsUN6fORf29CXlHkt7RvGFpSWtazQG1a/hGbFg7fZnhm
    DzF+vfipqYIeQ1KHY0nixkm5gMwdw7detoc7kCgXIeNKFl0dAJGZFFaUwbeMomtW
    HqZADjbUDMLZBvunILQOTCJtjFDfnxOGJFuTJzA+r8jvY9m24ohnO8UJAp0w/rSI
    AS4++RbBUrAbls7Cq4JcwFiwycVzXhGzA3NkVxlic4ebUyEiDnc3AgMBAAGjOTA3
    MA4GA1UdDwEB/wQEAwIFoDAMBgNVHRMBAf8EAjAAMBcGA1UdEQEB/wQNMAuCCWxv
    Y2FsaG9zdDANBgkqhkiG9w0BAQsFAAOCAQEAmr+8DGDbIWpU76hQ128EpieJAnOC
    +UMHLItl+IF6U4OZ2bn9L0LCvwfZYvv+yVgBnkwTyAQ/gsyNitw4xnmzdpbVpH4Z
    6c77Ewrhvrp/1J8iAvc+nHJmkS3XgS2ktN9a/VH/j8QkZi64lfhou6Pl6HNjhNMp
    /1Wm661kiNsGvAm4gaJiOQkSs5Po1D/7FZp/IpDtSvjmDaT+nrqZgO9kJwprWKzB
    A3L6tQXgdNocRcSx6yIxm/aH4SvJZWaas9W+emc/ITfhuZIueoy7fKWLX2+VqwVT
    8hYNfdrnF4zPT4p5ViqtPvKy6TaHp4EQSu5O9Cu+6NrpfHhoymO4HsUuLw==
    -----END CERTIFICATE-----
